language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
#  - hhvm # on Trusty only
#  - nightly
before_install:
  - nvm install 6.11
install:
  - composer install
  - npm install
before_script:
  - npm start 1>&2
  - sleep 3
  - npm run lint
script:
  - npm run test:coverage
  - npm run document-check && if [[ `cat "output/checkstyle.xml" | grep "<error "` != "" ]]; then exit 1; fi
before_deploy:
  - npm run document
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: output
  on:
    branch: master
after_success:
  - bash <(curl -s https://codecov.io/bash)
