language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm # on Trusty only
  - nightly
before_install:
  - nvm install 6.0
install: 
  - composer install
  - npm i process-nextick-args util-deprecate
  - npm install
before_script:
  - npm start 1>&2
script:
  - ./vendor/bin/phpunit
