language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm # on Trusty only
  - nightly
install: 
  - composer install
  - nvm use 6
  - npm install
before_script:
  - npm start 1>&2
script:
  - ./vendor/bin/phpunit
