language: php
dist: trusty

php:
 - '7.1'
 - '7.2'
 - '7.3'

cache:
  directories:
    - node_modules
    - vendor

before_install:
  - nvm install 8.11
  - sudo apt-get install graphviz

install:
  - composer install
  - npm install

before_script:
  - npm start 1>&2
  - npm run lint

before_deploy:
  - npm run document

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: output
  on:
    branch: master
    php: '7.2'

after_success:
  - bash <(curl -s https://codecov.io/bash)

